server.port=${PORT:8080}

Stripe_api_key=${Stripe_api_key}
Jwt_Signing_Key=${Jwt_Signing_Key}
EndPoint_Secret=${EndPoint_Secret}

spring.data.mongodb.uri=${SPRING_MONGODB_URI}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.username=${SPRING_DATA_REDIS_USERNAME}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}

spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}