spring.mongodb.uri=mongodb+srv://root:Cookie1.@cluster0.en0pykp.mongodb.net/BookingsApp?retryWrites=true&w=majority
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chandun3co@gmail.com
spring.mail.password=vkkq lcib achn iwtt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.data.redis.host=localhost
spring.data.redis.port=6379