server.port=${PORT:8080}
spring.mongodb.uri=mongodb+srv://root:Cookie1.@cluster0.en0pykp.mongodb.net/BookingsApp?retryWrites=true&w=majority
spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.data.redis.host=redis-12420.crce292.ap-south-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=12420
spring.data.redis.username=default
spring.data.redis.password=v69wxhIJHuGoh24V15ghJOnbX9XemvTC
spring.mail.username=chanduvalluri22@gmail.com
spring.mail.password=bkfq jphj jyau qqly